compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-09-12"
name = "com-trustscore"
main = "./index.ts"

[dev]
local_protocol = "https"
ip = "127.0.0.1"
port = 443

[assets]
run_worker_first = [ "/x/*", "!/_/*" ]
not_found_handling = "single-page-application"
directory = "./_/"
binding = "ASSETS"
